name: @name@
author: piratjsk
version: @version@
main: net.piratjsk.structgen.bukkit.StructGenPlugin
load: STARTUP
softdepend: [WorldEdit]

commands:
  structgen:
    aliases: [sg, structg, sgen]
